### PR TITLE
Change the default httpClient timeout from 20s to 200s to match readme file

### PR DESCRIPTION
**Pull request by qrdemole**

### CODE REVIEW

**Comment by qrdemole** [comment]
Will the recent changes be published on the nuget as a new version?

**Comment by yuzd** [comment]
i published a new version to nuget with default timeout 20s。
the default timeout of HttpClient is 100s . do you think 20s  is better then 200s?

**Comment by qrdemole** [comment]
200s is consistent with the readme. So I thought this value was somehow relevant. When I used the library I was expecting the default timeout of the HttpClient (100s).
So if the value of 200s or 20s is not something you are attached to then I would not set the timeout at all... and let it be set to the HttpClient default (100s) and remove the information from the readme.
I think you should make that decision though. I don't know why you needed to set the value in the first place.

**Comment by yuzd** [comment]
i changed the default timeout to 100s .
and changed the readme file. 
version : 1.0.3

**Comment by qrdemole** [comment]
Ok - thx!

**Pull request closed without merging**
